---
- hosts: all
  become: yes
 
  tasks:
  - name: Install openshit packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - wget
      - git
      - net-tools
      - bind-utils
      - yum-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct

  - name: upgrade all packages
    yum:
     name: '*'
     state: latest

